### ISSUE TITLE
Camel Debugger is not found in classpath. Please add camel-debug or camel-debug-starter JAR to your project dependencies.

### ISSUE THREAD

**Issue by raguser** [camel-tooling/camel-idea-plugin#666]
I'm using the Apache Camel plugin for Intellij IDEA, version 0.8.3.

Whenever I use the debugger, even if I just set a breakpoint in a plain Java class, I get the error message:

    "Camel Debugger is not found in classpath. Please add camel-debug or camel-debug-starter JAR to your project dependencies."

What is wrong?
What is meant by "camel-debug" or "camel-debug-starter" JAR. Where can I find this in the Maven repository?
Did I miss something?

I would be glad about any hint.

Kind regards

Stephan

**Comment by hamadaelnopy** [comment]
make sure that camel version is 3.15.0

**Comment by raguser** [comment]
Hello
thank you for your replay.
We are using Quarkus 2.5.0.Final with Camel 3.1.3.0.
In that case, do we have a chance to use the debugger?
Kind regards
Stephan

**Comment by raguser** [comment]
Hallo
Thank you for your quick reply.
It's a shame, but I think there's a reason for this limitation. Therefore, it would certainly not be purposeful to simply change the value. So we have to wait until Quarkus, Camel 3.15 supports.
Best regards
Stephan

**Comment by bvn13** [comment]
How to debug camel routes now?

![image](https://user-images.githubusercontent.com/682521/155194223-014d73e1-e4f0-4a34-a206-74f38ecb61d7.png)

**Comment by raguser** [comment]
Hello 

Meanwhile I upgraded to Camel Quarkus 2.7.1, based on Camel 3.15.0

If I set a breakpoint and try to debug, I get the error message:

"Camel Debugger is not found in classpath. 
Please add camel-debug or camel-debug-starter JAR to your project dependencies."

Then I add dependency in my pom.xml:

    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-debug</artifactId>
      <version>3.15.0</version>
    </dependency>

Now when I set a breakpoint and try to debug, I get the error message:

12:00:08.909 WARN [build-53] io.quarkus.arc.deployment.SplitPackageProcessor.splitPackageDetection - Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "org.apache.camel.impl.debugger" found in [org.apache.camel:camel-base-engine::jar, org.apache.camel:camel-debug::jar]
...
	[error]: Build step org.apache.camel.quarkus.core.deployment.CamelProcessor#factoryFinderResolver threw an exception: java.lang.NoClassDefFoundError: org/apache/camel/spi/DebuggerFactory
...
Caused by: java.lang.ClassNotFoundException: org.apache.camel.spi.DebuggerFactory
...
	[error]: Build step org.apache.camel.quarkus.core.deployment.CamelProcessor#factoryFinderResolver threw an exception: java.lang.NoClassDefFoundError: org/apache/camel/spi/DebuggerFactory
...
Caused by: java.lang.ClassNotFoundException: org.apache.camel.spi.DebuggerFactory
...
Caused by: java.lang.NoClassDefFoundError: org/apache/camel/spi/DebuggerFactory
...
Caused by: java.lang.ClassNotFoundException: org.apache.camel.spi.DebuggerFactory
...

Do you have any idea what may be wrong?

Kind regards 

Stephan

**Comment by davsclaus** [comment]
I created a ticket about the split package to be fixed in Camel 3.16.0
https://issues.apache.org/jira/browse/CAMEL-17752

**Comment by davsclaus** [comment]
So try again when camel-quarkus has upgraded to camel 3.16

**Comment by raguser** [comment]
Many thanks for your reply. I will do so.

Kind regards

Stephan Rudolph
________________________________

**Comment by bvn13** [comment]
How to solve this issue on camel+springBoot project? Without Quarkus.
